
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = 's\xb9\xe1\x9dU\xf4<\xb5\xfa\xfc&\xfc\xee\xa9\xf2\x90'
    
_lr_action_items = {'integer':([0,3,],[2,2,]),'plus':([1,2,4,],[3,-2,3,]),'$end':([1,2,4,],[0,-2,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,3,],[1,4,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression plus expression','expression',3,'p_expression_plus','main.py',7),
  ('expression -> integer','expression',1,'p_expression_num','main.py',11),
]
